### ISSUE TITLE
Enhance the Issuer section to allow clicking through to issuing certificate tab

### ISSUE THREAD

**Issue by glawrence** [april/certainly-something#11]
The tabs show the site, the intermediates and the root certificates. However it would be nice if there was a hyperlink (preferably highlighted, to stand out) on the certificate that when clicked, switched to the tab with the details of the issuing certificate. This would make navigation easier and more natural.

The trusted roots will need handling differently but it would be nice if it highlighted they were trusted by the browser itself.

**Comment by MauAraujo** [comment]
Hi @glawrence, I think your idea would indeed make the navigation feel more natural to the user. The way I understood, I propose to add a link like this:
![quest](https://user-images.githubusercontent.com/19579265/53686955-d5036600-3cf3-11e9-8329-f5ca9b05a681.png)
Is it ok or maybe I misunderstood? 
@april, if you think this would be a nice addition, please let me know so I can start working on this. Thank you for your feedback.

**Comment by glawrence** [comment]
Hi @MauAraujo that looks great, thanks. I think the "Common Name" link would need highlight to show it was a link but yes you have captured in a picture what I was thinking, so nice job!

**Comment by noorfathima11** [comment]
@MauAraujo are you still working on this?

**Comment by MauAraujo** [comment]
Yes, I am still working on this.

**Comment by glawrence** [comment]
@noorfathima11 this is in PR #36 which I think is almost complete, which is good

**Comment by april** [comment]
This was fixed in #36.
