### ISSUE TITLE
Open "Certificate Viewer" tab to the right of current tab

### ISSUE THREAD

**Issue by glawrence** [april/certainly-something#12]
At the moment when Certificate Viewer opens a new tab to show all the certificate information it adds a tab on the end, far right. I work with lots of tabs open, so I would like it to work like "View Page Source" and open a new tab to the immediate right of the current page, so it is closer and easier to find

**Comment by hardfalcon** [comment]
You could set the "browser.tabs.insertAfterCurrent" preference to true in about:config - this would affect all new tabs, and not just certainly-something.

browser.tabs.create() also does accept an index parameter, but sticking to the (user configurable) default behavior seems more reasonable to me.

**Comment by rugk** [comment]
> browser.tabs.create() also does accept an index parameter, but sticking to the (user configurable) default behavior seems more reasonable to me.

I don't agree. As this one argument by @glawrence is really convincing:
> I would like it to work like "View Page Source" and open a new tab to the immediate right of the current page

As this add-on also similarly shows information/data about the current site, I'd say it is reasonable if it behaves the same.

**Comment by april** [comment]
I think this is a reasonable ask. I'll try to get it in the next version.

When I'm developing, I only test with a few open tabs so I don't usually notice it that much.  :)

**Comment by glawrence** [comment]
Nice thinking @hardfalcon I had forgotten that option, good call.

Thank for your support @rugk I am a fan of consistency and I think an addon/extension/plugin should be just that and feel part of the application

@april clearly this is not a high priority issue but thank you for taking the suggestion on board, although I should really do a pull request as I reckon I could do this myself....

**Comment by april** [comment]
BTW the fix for this has been pushed on AMO in version 1.0.2.

**Comment by glawrence** [comment]
I have updated and it works, that is brilliant, thank you very much @april
