### ISSUE TITLE
Tabs require reload

### ISSUE THREAD

**Issue by rugk** [april/certainly-something#16]
…if you do install the add-on without reloading the tabs, the cert tab it opens, directly closes itself afterwards.

STR:
1. Install add-on.
2. Switch to tab.
3. Click cert icon.

What happens:
New tab opens and closes.

What should happen:
Either show an error, or work around the problem, if possible.

Firefox 63.0a1 (2018-08-03) (64-bit)

**Comment by april** [comment]
This is actually a much more difficult problem than it appears to be. A lot of people would be absolutely pissed if I force reloaded the tab in order to get the information from the browser.

I could probably open an error page instead?

**Comment by rugk** [comment]
AFAIK you cannot get it afterwards, because you need the load information.

Yes, an error would be fine.
Maybe, if you can, just as a popup with a "reload [website]" button. (Added "website" to make sure it is obvious it reloads the website, not the popup or so.)

**Comment by april** [comment]
I pushed this to the published add-on - is everything working okay for you?

**Comment by rugk** [comment]
Unless this is expected, no:

![certsomet](https://user-images.githubusercontent.com/11966684/44159405-8ffd4680-a0b7-11e8-9c89-8af92ba4c9f3.gif)

**Comment by rugk** [comment]
Debug console error message is:
> Error: Could not establish connection. Receiving end does not exist. background.js:1:2568

**Comment by april** [comment]
Yeah I'm trying to figure out what's going on.  :(

**Comment by april** [comment]
Okay, try updating now (version 1.0.8) and tell me if things are working a bit better for you.

**Comment by april** [comment]
That's... very strange. Uhh. I'm not having this problem on any of my machines. Does it still happen if you restart Nightly?

**Comment by april** [comment]
I've asked other people who use it and they don't have any issues either.  :(

**Comment by rugk** [comment]
Okay, yes, also works here right now. Anyway, as for this issue, the issue stays the same. It does not do anything when tab is not reloaded.
