### ISSUE TITLE
Id??

### ISSUE THREAD

**Issue by rugk** [april/certainly-something#17]
https://github.com/april/certainly-something/blob/ab5577ea3ac5c29d1393227a95cc990f9e5532c6/src/manifest.json#L21

Are we supposed to brute-force that? :open_mouth:

**Comment by april** [comment]
It's a string that has been piped to sha256.

If you can figure out what it was, I'll buy you a box of donuts.  :)

**Comment by rugk** [comment]
I would bet you used a salt and made brute-forcing impossible… :laughing:
