### ISSUE TITLE
Support extension 1.3.6.1.4.1.311.20.2

### ISSUE THREAD

**Issue by alexandrul** [april/certainly-something#19]
It's used for our internal organization certificates.

It's also mentioned here: https://support.microsoft.com/en-us/help/287547/object-ids-associated-with-microsoft-cryptography

**Comment by april** [comment]
For my reference:

https://censys.io/certificates?q=parsed.unknown_extensions.id%3A+1.3.6.1.4.1.311.20.2
https://backup.hs-bremerhaven.de/

**Comment by pavithra-es** [comment]
I'd like to work on this.

**Comment by april** [comment]
Sounds great! Go for it!

**Comment by MauAraujo** [comment]
Hey @april is this still taken? I figured out how to support this extension, and would like to implement it if it is available.

**Comment by pavithra-es** [comment]
@MauAraujo , I'm already working on this. Seems like #27 is still open, it is similar to this one, do check it out. :)

**Comment by MauAraujo** [comment]
Sorry @pavithra-es, it's just that every issue here seems taken. Thanks for pointing me out! I'll start working on that one.

**Comment by april** [comment]
See also: https://github.com/PeculiarVentures/PKI.js/issues/223
