### ISSUE TITLE
Support extension OID 1.3.6.1.4.1.311.21.7

### ISSUE THREAD

**Issue by april** [april/certainly-something#2]
https://censys.io/certificates?q=parsed.unknown_extensions.id%3A+1.3.6.1.4.1.311.21.7

**Comment by glawrence** [comment]
I have just seen this at https://docs.microsoft.com/ was going to report as advised but you are ahead of me!

**Comment by Panto1212** [comment]
Hey April, this looks interesting. I request to be assigned to this please. Thanks

**Comment by twisted-sres** [comment]
Hey, can I take this up? I am an outreachy applicant.

**Comment by april** [comment]
@Panto1212, did you still want this? Otherwise, @twisted-sres can take it on it looks like.

**Comment by Panto1212** [comment]
Yes I do please

**Comment by twisted-sres** [comment]
Hey, what are the steps to reproduce this? Where is this actually not supported?

**Comment by glawrence** [comment]
> Hey, what are the steps to reproduce this? Where is this actually not supported?

@twisted-sres if you visit https://docs.microsoft.com/en-gb/, launch "Certainly Something" and scroll to the bottom you will see a message: _"Please open up an issue at Certainly Something, noting the website and unsupported extension identifiers. Thanks!"_

So the aim is to support the OID in the title of this issue and remove the number from the message. Same applies for #3 so this message would be useful for @akshithashetty as well. Do look at the other issue as April posting a useful link there

**Comment by twisted-sres** [comment]
By launching certainly-something, do you mean opening the certificate viewer? I can't find the message at the bottom

**Comment by twisted-sres** [comment]
Hey @Panto1212 ,sorry I already started working on this by the time you answered. I have opened #27 and #28, you can take any one of them. Thanks:)

**Comment by glawrence** [comment]
@twisted-sres yes I do mean open the certificate viewer for the Microsoft site. When I do this I see something like this:

![image](https://user-images.githubusercontent.com/1067355/53643948-4fb57e00-3c2d-11e9-97c3-6512197ed9fe.png)

Hopefully that makes sense now.

**Comment by noahwalugembe** [comment]
Is this issue still open some some one else to contribute on

**Comment by april** [comment]
See also: https://github.com/PeculiarVentures/PKI.js/issues/223

**Comment by april** [comment]
This was fixed in ad1b88e1668299b8fb6bf80f7deecd1443df5b68.
