### ISSUE TITLE
Click on address bar icon opens an empty tab

### ISSUE THREAD

**Issue by kinglike1337** [april/certainly-something#21]
The addon does not seems to work in my firefox installation.
After the click on the address bar addon icon, a new tab opens but stays empty.

URL for new tab:
moz-extension://b62c6b91-8a2e-423a-8708-d6265879c617/viewer/index.html?tid=11

In the browser console the following error is logged:
TypeError: (new Date(...)).toString(...).match(...) is null
index.js:1:133990

Tested on github, amazon and some other sites.

Environment:
Firefox 62.0.3 (64-Bit / Windows)
Profile without other extensions
Addon version 1.1.0 installed from AMO

**Comment by kinglike1337** [comment]
The error maybe triggered by this line of code:
https://github.com/april/certainly-something/blob/25a51708a0671057b4eefb9186a5281d9d097762/src/viewer/js/der.js#L74

"new Date().toString()" evaluates to "Sat Oct 20 2018 13:42:23 GMT+0200" (german timezone).

**Comment by april** [comment]
Awesome, thanks! I'll work on this next week. Sorry that things are broken for you, but I really appreciate you filing the bug.  :)

**Comment by april** [comment]
Hey, @kinglike1337? I just published version 1.1.1 today on AMO. Could you let me know if that fixes the bug for you?

Thanks again so very much!

**Comment by kinglike1337** [comment]
The addon now works as desired. Finally a good replacement for SSLeuth.
Thank you very much for your efforts and the quick fix.

**Comment by april** [comment]
Wonderful! That is great to hear! Thanks again for the bug report.  :)

Over time, I'd like to have more SSLeuth type information in the extension, but it may be a little while. There is a bug for it, however, if you'd like to follow it:

https://github.com/april/certainly-something/issues/9
