### ISSUE TITLE
Use PageAction dropdown instead of new tab on desktop

### ISSUE THREAD

**Issue by Riajyuu** [april/certainly-something#24]
you can use window.navigator property to determine whether it is on desktop right now.

**Comment by rugk** [comment]
So is this a dupe of https://github.com/april/certainly-something/issues/6?

**Comment by rugk** [comment]
What exactly do you mean by "PageAction dropdown"? Can you show a screenshot or mockup?
The "button behaviour" for opening in a new tab is already there, as you can obviously see…

**Comment by april** [comment]
What do you think should be visible on the dropdown? I think most people are using this because they want to see the full certificate, but I honestly don't have any metrics on the matter.

**Comment by Riajyuu** [comment]
@april 
because Firefox Android has limited ability to view certificate compared to Chrome for Android.
Perhaps make an Android branch that has pageactoon dropdown?

**Comment by april** [comment]
I'm going to close this, because I don't think I'm going to fix it. PageActions don't show enough information to disable a full certificate chain, and the small size is part of why the Firefox certificate viewer is so hard to use.
