### ISSUE TITLE
Improve README to include installation instruction for web-ext

### ISSUE THREAD

**Issue by twisted-sres** [april/certainly-something#26]

**Comment by twisted-sres** [comment]
Running 'npm install --global web-ext' helps us install web-ext globally. Instead of keeping the repo link for web-ext, we can keep this command and just a single line description about what web-ext is (A command line tool to help build, run, and test web extensions), so that it won't cause much confusion for the beginners. We can keep the repo link also as "For more details, refer to this repo link".

**Comment by twisted-sres** [comment]
@april , let me know how if you like the suggestion, I will create a PR. Thanks :)

**Comment by april** [comment]
Sure, it's a fine idea and I would gladly accept it, but I don't think this is really sufficient to count as fixing a bug for the purposes of evaluation for the Outreachy program.  :)

**Comment by april** [comment]
Whoops, didn't meant to close it.  :)

**Comment by twisted-sres** [comment]
Yeah, just realised this would be nice to have while setting up the project. Working on an another bug for evaluation :)

**Comment by NidhiKJha** [comment]
This issue should be closed since the pr concerning this has been merged.
