### ISSUE TITLE
Support extension OID 1.3.6.1.4.1.311.21.2

### ISSUE THREAD

**Issue by twisted-sres** [april/certainly-something#27]
Just like #19

**Comment by twisted-sres** [comment]
@april I am an Outreachy applicant, let me know if I could take this up

**Comment by monikamaheshwari** [comment]
@april I am an outreachy applicant, can I work on this issue

**Comment by MauAraujo** [comment]
Hi! @april, is it ok if I start working on this one? As I said in #19, I figured out how to implement this.

**Comment by april** [comment]
@monikamaheshwari looks like they were the first to comment. @monikamaheshwari, do you still want this?

**Comment by NidhiKJha** [comment]
@April I would like to work on this issue

**Comment by april** [comment]
@MauAraujo Do you want this? It has been 4 days since @monikamaheshwari commented. If not, we can pass it off to @NidhiKJha. Thanks!

**Comment by outdoorsole** [comment]
Hello @april I would like to work on this issue if no one will take it -- although I see @NidhiKJha is next in line ahead of me, so if there happens to be another issue I would be able to work on, would be happy to!

**Comment by monikamaheshwari** [comment]
Hi sorry for late reply. I want to do this

**Comment by april** [comment]
Sorry, @monikamaheshwari, there are already so few bugs available that I couldn't keep it unclaimed for any longer.

**Comment by MauAraujo** [comment]
So @april, is it alright if I start working on this? I am available and could start implementing it right away.

**Comment by april** [comment]
Yes please, go ahead.

**Comment by NidhiKJha** [comment]
My apologies. But I had already started to work on this and opened a PR when @april  commented it last time and @MauAraujo  you didn't reply.

**Comment by MauAraujo** [comment]
@NidhiKJha Sorry if I didn't reply right away, but I was waiting for @april to assign the issue since @monikamaheshwari commented immediately after and she was the first to claim this. However, I believe that I was next in turn to work on this, and I would have liked that to be respected as I did the same. Any thoughts on this @april ?

**Comment by april** [comment]
@MauAraujo Go ahead and submit a PR as well. I'll likely only accept one, but it will give a good point of evaluation.

**Comment by april** [comment]
@twisted-sres, when you submitted this bug, was there a website you found it in use on?

**Comment by april** [comment]
See also: https://github.com/PeculiarVentures/PKI.js/issues/223
