### ISSUE TITLE
Support extension OID 1.3.6.1.4.1.311.21.1

### ISSUE THREAD

**Issue by twisted-sres** [april/certainly-something#28]
@april I am an outreachy applicant, let me know if I could take this up

**Comment by twisted-sres** [comment]
Just like #19

**Comment by april** [comment]
Works for me, but please just pick one of these.  :)

**Comment by Paarmita** [comment]
Hey, @april Can I take this one as my first contribution to certainly-something?

**Comment by sudhirsaharan** [comment]
@twisted-sres  @Paarmita  Hey there , i am done with the setup of mozilla by following this link : https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Windows_Prerequisites
Now for contributing on certainly something, how do i proceed with further setup process . Can you please tell , i am new to this .

**Comment by april** [comment]
@Paarmita Loooks like @twisted-sres took the other one, so go ahead.

**Comment by asishkr123** [comment]
@april  i am an outreachy applicant too , i need to contribute. so are you opening any new issues or  will i have to contribute to the project myself. i know i am a bit late in the application process but any help will be appreciated.

**Comment by Paarmita** [comment]
@april It looks like there should be some more modification in the https://github.com/april/certainly-something/pull/29 PR as this is also an OID Certificate, so should I wait for the PR to be merged or create a new one?

**Comment by devGeorgeOwi** [comment]
@april I know i came in a bit late, but please is there any issues that i can take on? will be expecting more issues thanks

**Comment by april** [comment]
@Paarmita go ahead and create a new one, although I would generally recommend that you consider using the same data structure.  :)

**Comment by Paarmita** [comment]
Thanks, 👍 Will create a new one then following following instructions from the previous one.

**Comment by noahwalugembe** [comment]
Hi @april i have came in a bit late, and i cant find any bug to solve. Is it okay for you to help me out.
I really want to contribute.

**Comment by noahwalugembe** [comment]
@april are you opening any new issues soon. i know i am a bit late in the application process but any help will be appreciated.

**Comment by noahwalugembe** [comment]
@april Can i also work on this issue Support extension OID 1.3.6.1.4.1.311.21.1 or i can wait for new issues

**Comment by april** [comment]
See also: https://github.com/PeculiarVentures/PKI.js/issues/223
