### ISSUE TITLE
Support extension OID 1.3.6.1.4.1.311.21.10

### ISSUE THREAD

**Issue by april** [april/certainly-something#3]

**Comment by glawrence** [comment]
I have just seen this at https://docs.microsoft.com/ was going to report as advised but you are ahead of me!

**Comment by akshithashetty** [comment]
Hi , I would like to start working on this one. Could you please guide me on getting started?

**Comment by april** [comment]
https://support.microsoft.com/en-us/help/287547/object-ids-associated-with-microsoft-cryptography has some good documentation on the certificate OIDs, and Censys can help you find them.  :)

**Comment by SeverusHO** [comment]
Hey April, is this being worked on?

**Comment by akshithashetty** [comment]
Yes, I am working on this one.

**Comment by april** [comment]
See also:

https://github.com/PeculiarVentures/PKI.js/issues/223

**Comment by april** [comment]
This was fixed in ad1b88e1668299b8fb6bf80f7deecd1443df5b68.
