### ISSUE TITLE
Change `arrow` pointer to `I`pointer on selecting text

### ISSUE THREAD

**Issue by Paarmita** [april/certainly-something#33]
**Current problem**
On selecting any text in the extension, the arrow pointer remains the same and doesn't change.

**Expected Behaviour**
The `arrow` icon should change to a `pointer or I` icon on selecting text, in order to show that text has been selected.

![screenrecording20190304at7](https://user-images.githubusercontent.com/26546816/53737419-7d5f2900-3eb2-11e9-854e-c58adf16c374.gif)

**Comment by uimarshall** [comment]
Hi April,

I am an outreachy applicant and looking forward to contributing to this project.
I want to find out if I could work on it.

**Comment by april** [comment]
If you want to fix this, that would be great @Paarmita. Thanks!

**Comment by Paarmita** [comment]
@april Thanks. I will work on it.

**Comment by april** [comment]
Fixed in #37.
