### ISSUE TITLE
Change arrow pointer to 'hand' pointer when selecting tab 

### ISSUE THREAD

**Issue by RizwanSyed357** [april/certainly-something#34]
When  certainly-something is running in the Firefox browser, the `arrow` pointer remains an arrow pointer when clicking on the 'tab' options' (i.e. : twitter.com, DigiCert SHA2 High Assurance Server CA, DigiCert High Assurance EV Root CA (built-in root)).

It should change to a hand pointer, in order to show the user that a 'tab' option is being hovered over. 

 (please see image attached to this post) 

![certainly-something bug 1](https://user-images.githubusercontent.com/10325793/53766562-1437df80-3ecb-11e9-91bd-3acac64e4c20.png)

**Comment by RizwanSyed357** [comment]
(I am an Outreachy applicant and would like to fix this bug please, if possible. May it be assigned to me? Cheers )

**Comment by rugk** [comment]
See also: https://github.com/april/certainly-something/issues/33

**Comment by april** [comment]
This was also fixed in #37.
