### ISSUE TITLE
Add a 'report a bug' link to the extension 'site information' box 

### ISSUE THREAD

**Issue by RizwanSyed357** [april/certainly-something#35]
It would be good to add a section of text reading 'report a bug' to the certainly-something extension window (please see pic attached to this bug report) that opens in the browser. That text can link back to this Github repo, where users can also read the Readme file if they wish.

![certainly-something bug 2](https://user-images.githubusercontent.com/10325793/53767506-f6b84500-3ecd-11e9-9ff4-710c8a7a5bbb.png)

**Comment by RizwanSyed357** [comment]
(I am an Outreachy applicant myself - I would like to work on this bug if it sits ok with you. Cheers :) )

**Comment by april** [comment]
I'm not sure anybody ever clicks on that ℹ️, but if you can add a Report a Bug option there that would be great. That said, as the eventual project is to integrate it into Firefox, it would no longer be an extension.  :)

**Comment by RizwanSyed357** [comment]
Hi @april , I am happy to embed a Report a Bug option in the actual certificate itself then. Does that sound more useful than adding one to the window that opens immediately after the user clicks information_source  ?

I imagine this would make more sense, given recent issues/bugs that were closed were centred around the UI of the certificate itself.

**Comment by april** [comment]
I don't know if it's particularly necessary, given that most people won't be reporting bugs and those that do shouldn't have too much difficulty finding the place to report them. I don't think I would want it to be on every certificate viewing page.

**Comment by RizwanSyed357** [comment]
I am happy to find another bug to work on, April.

**Comment by RizwanSyed357** [comment]
I understand. I'll make a Report a Bug option as I suggested in my first post above, then.

**Comment by RizwanSyed357** [comment]
Hi @april  , I have given this some thought and would prefer to work on something that might help, even in a small way.  May you please close this issue? I have posted another one that I would prefer to work on.

**Comment by rugk** [comment]
Is this even possible to solve this issue in a Firefox add-on/WebExtension?
Without it being integrated into Firefox, it cannot show anything thee.

**Comment by april** [comment]
I didn't think it was possible, but I assume that @RizwanSyed357 had checked to see before they offered.  :)
