### ISSUE TITLE
Making the critical extension stand out 

### ISSUE THREAD

**Issue by km-js** [april/certainly-something#39]
By giving the critical extensions' icon some color like red can make them stand out
![screenshot_11](https://user-images.githubusercontent.com/39799586/53815256-50307a80-3f87-11e9-8e20-52d3ed7afc3e.png)

**Comment by april** [comment]
Critical is not that critical, it's more means required than anything.

Most certificate viewers don't make it particularly stand out, and I don't think it's super necessary here. Sorry!
