### ISSUE TITLE
Support "uploading" a cert chain

### ISSUE THREAD

**Issue by april** [april/certainly-something#4]
Have a spot in the interface where people could "upload" a cert and view it.

**Comment by myfreeweb** [comment]
I accidentally discovered [this addon](https://addons.mozilla.org/en-US/firefox/addon/certificate-viewer-for-humans/) — interesting idea, right click on certificate text to view.

**Comment by exturingmachina** [comment]
Hello, would it be okay if I start working on this? Any suggestions of how I should go about it are appreciated. Thank you.

**Comment by monikamaheshwari** [comment]
Hi, want to work on this issue.

**Comment by april** [comment]
@exturingmachina, do you still want the issue? Otherwise, @monikamaheshwari can take it on.

**Comment by exturingmachina** [comment]
Yes, I want to work on it.

**Comment by april** [comment]
Yes go right ahead then.  :)

**Comment by karansapolia** [comment]
Hey @exturingmachina! Are you still working on this one? I want to work on this if its available.

**Comment by exturingmachina** [comment]
I'm still working on it. It was assigned yesterday :)

**Comment by monikamaheshwari** [comment]
Hey after @exturingmachina I would like to work on it.

**Comment by monikamaheshwari** [comment]
@april If @exturingmachina is not working on it then I would like to work on it.

**Comment by exturingmachina** [comment]
Have at it.

**Comment by monikamaheshwari** [comment]
@april Is there any preference, where to give that upload button.

**Comment by april** [comment]
I would probably add it to a right-click submenu of the `pageAction` by using `contextMenus` with a `page_action` context type. I haven't done it personally, but I believe it is possible and is probably the best route.

**Comment by monikamaheshwari** [comment]
I have added like this :
![Screen Shot 2019-03-15 at 9 35 14 PM](https://user-images.githubusercontent.com/17271005/54445233-59c99780-476a-11e9-8cdd-ce5ee36d67c8.png)

Is this correct?

**Comment by april** [comment]
That looks good to me.

**Comment by monikamaheshwari** [comment]
On clicking this button what kind of action is required. Can you guide me please.

**Comment by april** [comment]
I believe given the limitations of WebExtensions, you would have to open up a webpage with an input field where users could upload a file with the file picker.  :)

**Comment by april** [comment]
Fixed in dd43a1e3488c29e488742690b3a3fd6711304103.
