### ISSUE TITLE
All elements under two-line left-side value shift downwards 

### ISSUE THREAD

**Issue by RizwanSyed357** [april/certainly-something#41]
Whenever the user's pointer hovers over a row whose left-side value is two-lines long, all the elements beneath that row move down slightly. 

This can be a bit annoying when you are scrolling and looking at multiple elements quickly. 

See this gif: 

![githubbug-2019-03-05_21 41 51](https://user-images.githubusercontent.com/10325793/53839915-a35afb00-3f90-11e9-983b-84f44b56917c.gif)

**Comment by RizwanSyed357** [comment]
(Obviously - would like to do this myself as an Outreachy applicant.)

**Comment by noahwalugembe** [comment]
Am sorry to ask this how did you get to this GUI https://user-images.githubusercontent.com/10325793/53839915-a35afb00-3f90-11e9-983b-84f44b56917c.gif

I can only run the code but not be able to access the GUI pleas guide me out

**Comment by april** [comment]
Sure, go ahead and send a PR.  :)

**Comment by noahwalugembe** [comment]
> Sure, go ahead and send a PR. :)

I have got this response in my mail can i work on it or its for RizwanSyed357

**Comment by RizwanSyed357** [comment]
@noahwalugembe  go ahead and solve it. I am working on other things now. Wish you all the best.

**Comment by noahwalugembe** [comment]
Thanks @RizwanSyed357

**Comment by noahwalugembe** [comment]
> Sure, go ahead and send a PR. :)

@april I have fixed the .panel-list-item css by hiding overflow. actuary at this point elements with two line sentence left or right side can't cause downer elements to shift  on mouse hover. 
Can i make this as my first git commit.

/* overrides to extension.css */
.panel-list-item {
  height: inherit;
  min-height: 24px;
  cursor: text;
  overflow: hidden;
  max-height: 35px;
}

**Comment by april** [comment]
Can I ask why the max height? But sure.

**Comment by noahwalugembe** [comment]
> Can I ask why the max height? But sure.

When you resize the browser window so as to mimic mobile device screen panel-list-item with much text word-breaks or over flows hence creating more lines and this affects the div heights of over elements below. Hence resulting in effects like (div slightly shifting  from  their position  when  hovering on an element that changes size above it)

With max-height: 35px; or 40 px; I'm telling the container to not expand more than optimal 30px in height so as not to affects other div heights. and then i use overflow: auto instead. That will only show scrollbars when the content overflows

Before implementation
![before](https://user-images.githubusercontent.com/27782388/54338342-ab770280-4642-11e9-93b5-e5d5f24553ab.gif)



After implementation
![after](https://user-images.githubusercontent.com/27782388/54338332-a0bc6d80-4642-11e9-9e57-44baf7c785ab.gif)

**Comment by noahwalugembe** [comment]
Hi @april is this work okay

**Comment by april** [comment]
Sorry, but I'm afraid having scrollbars for an individual field is a very poor experience. It should work the same as now but without the slight shifting upon hovering.

**Comment by noahwalugembe** [comment]
> Sorry, but I'm afraid having scrollbars for an individual field is a very poor experience. It should work the same as now but without the slight shifting upon hovering. Also each line is huge (requiring a lot of scrolling), and this doesn't look anything like the original implementation.

Okay let me work on it again

**Comment by monikamaheshwari** [comment]
Hi, I was trying to solved this problem and have solved it without affecting existing design. Let me know if I could send a PR for this :)
