### ISSUE TITLE
When scrolling down Certificates panel does not stick on top

### ISSUE THREAD

**Issue by asraqadri** [april/certainly-something#44]
When scrolling Certificates panel does not stick on top. Instead of scrolling up to switch between sub-header I think if we stick the certificate panel on top it will look good and easy to navigate between sub-headers.

![output_4qevri](https://user-images.githubusercontent.com/46629032/53862563-c5df2980-400d-11e9-8353-047ab9ba72b5.gif)

**Comment by asraqadri** [comment]
As I am an Outreachy applicant I would like to do this myself.

**Comment by april** [comment]
It does already do this, but it depends on the size of your viewport. That div is already marked with `position: sticky`.  :)

<img width="1281" alt="screen shot 2019-03-06 at 3 05 11 pm" src="https://user-images.githubusercontent.com/230528/53913583-4bb8a000-4021-11e9-900a-729799a2e788.png">
