### ISSUE TITLE
Tab bar has one vertical line on the left side and no line on right side

### ISSUE THREAD

**Issue by monikamaheshwari** [april/certainly-something#47]
Just a small display fix. The design should be consistent. As I am outreachy applicant so I would like to solve this issue.

![Screen Shot 2019-03-09 at 1 19 06 PM](https://user-images.githubusercontent.com/17271005/54068057-06d57900-426e-11e9-90d7-5c6363e0b91e.png)

**Comment by april** [comment]
Sure, that would be great.

**Comment by april** [comment]
I fixed up your commit in 67c60309f9b7152ba8d77e66eb4b46572bce38af and that should close this out.  :)

**Comment by monikamaheshwari** [comment]
Thanks :)
