### ISSUE TITLE
Direct people on how to access the certificate viewer web page

### ISSUE THREAD

**Issue by noahwalugembe** [april/certainly-something#49]
Hi @april .
One of the challenge i faced previously with certainly-something documentation was to figure out on how to access the certificate viewer web page after  runing

 {
$ npm run-script watch
$ web-ext run --browser-console -s build --start-url 'https://badssl.com/'
}

is it okay if i can add this instruction{

After $ web-ext run --browser-console -s build --start-url 'https://badssl.com/' Then wait for a new web fire fox browser window to open and then it browse any website with https. After that click on the padlock item on the right side of address bar
![image](https://user-images.githubusercontent.com/27782388/54390900-9044db00-46b4-11e9-9f78-8884ebd003b8.png)

}

**Comment by april** [comment]
In general, people who are going to be developing with the extension will already know how it is and how to use it. I don't think this is necessary, sorry.

**Comment by noahwalugembe** [comment]
Okay @april am really trying to search for a new thing to work on and if you get any new bug on your side pleas extend it to me again
