### ISSUE TITLE
Still not working also on Firefox 66 (Android)

### ISSUE THREAD

**Issue by PeopleInside** [april/certainly-something#58]
The extension is no more working on Firefox 66.
Is installed but no options is showed to check the certificate.
https://bugzilla.mozilla.org/show_bug.cgi?id=960447#c14

**Comment by PeopleInside** [comment]
Seems the bug was introduced in the version 1.2.0 the version 1.1.2 works
https://bugzilla.mozilla.org/show_bug.cgi?id=960447#c19

**Comment by april** [comment]
I'm working this now, sorry for the delay!

**Comment by PeopleInside** [comment]
@april  Thank you!

**Comment by april** [comment]
Okay, this has been fixed in version 1.2.3. Sorry for the delay!  :)

**Comment by PeopleInside** [comment]
Thank you very much @april

**Comment by april** [comment]
You're very welcome. Could you let me know if things are working (or not working) for you? Thanks!

**Comment by PeopleInside** [comment]
Umh... just install the extension here: https://addons.mozilla.org/en-US/firefox/addon/certainly-something/ ?
I was using a previous version, seems it's working.. i believe :) Seems you have done a great job ;-)

I love your avatar and smile :) thanks again!

**Comment by april** [comment]
Peeeeeerfect, thank you! And thanks.  :)
