### ISSUE TITLE
Fit to a popup

### ISSUE THREAD

**Issue by Madis0** [april/certainly-something#6]
The extension could compact the interface a bit to make it fit to a popup, opening a new tab with left-aligned text isn't very easy to read on a big monitor.

For example:

- collapse Extensions by default
- remove gray striped headers if they have only one value (e.g remove "Authority Key ID" if there is one "Key ID")

**Comment by april** [comment]
Popups have a lot of shortcomings, namely that they're not persistent and they can only be so high, which leads to a lot of scrolling. I may explore other ways of displaying things (such as a sidebar) someday, but there's generally too much information to fit nicely into a popup.

Thank you for the feedback! I am definitely exploring other display options.
