### ISSUE TITLE
Explain 3 tabs

### ISSUE THREAD

**Issue by Madis0** [april/certainly-something#7]
Could you please elaborate, what is the usefulness of the 3 tabs. From what I understand:

1. The certificate for the site (same info the built-in page info displays, that makes sense)
2. The certificate for the CA (for verifying if the CA is not compromised?)
3. The root certificate (for verifying if the root is not hijacked by computer malware?)

**Comment by rugk** [comment]
I guess this add-on is not about verifying anything (you can hardly do anyway). It's just giving you some information. The tabs show all certificates used - root, intermediate and leaf.

**Comment by april** [comment]
It's displaying the entire certificate chain (as @rugk said), which the browser used to verify the leaf (end-entity) certificate.

Every browser shows the entire chain in its certificate viewer, including Firefox.
