### ISSUE TITLE
RFE: Show whether extensions are marked as "critical" or not

### ISSUE THREAD

**Issue by hardfalcon** [april/certainly-something#8]
If would be nice if the UI showed whether an extension is marked as "critical" or not.

**Comment by april** [comment]
I actually have this code sort of in there already, but I'm struggling to find a good way to represent it that doesn't take up a ton of space.

I don't know how much people typically care about critical sections. That said, I feel like I should probably find a way to show it given that most browsers show it.

**Comment by hardfalcon** [comment]
Perhaps put a "stop sign" emoji next to it, and give that emoji a tooltip that say "Critical"?
https://emojipedia.org/octagonal-sign/
